; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = espidf

; Set upload limits to 4MB
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304

board_build.partitions = partitions.csv

; Force the SDK config to use 4MB (Critical for ESP-IDF) | Otherwise resulting in an Warning (expected size = 8MB)
board_build.esp-idf.sdkconfig_options = 
    CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y
    CONFIG_ESP_MAIN_TASK_STACK_SIZE=8192
    CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE=8192

; AgIsoStack++ Library von GitHub
lib_deps = https://github.com/Open-Agriculture/AgIsoStack-plus-plus.git

build_type = debug
upload_protocol = esptool

monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
monitor_filters = esp32_exception_decoder

; Deine IOP-Datei in die Firmware einbetten
board_build.embed_files = VT_object_pool/Zirkon12.iop